import React, { useEffect, useState } from 'react';
import Venushead from '../assets/Frame 3.png'
import Midjour from '../assets/Logo.png'
import Openai from '../assets/openai.png'
import "./Hero.css"
import { Link } from 'react-router-dom';
import { CarouselDemo } from '../components/demo/CarouselDemo';
import { AccordionDemo } from '@/components/demo/Accordian';
import Footer from '@/components/Footer';



import { Card, FormField, Loader } from '../components';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post._id} {...post} />)
    );
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState(null);

  const fetchPosts = async () => {
    setLoading(true);

    try {
      const response = await fetch('https://dalle-arbb.onrender.com/api/v1/post', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const result = await response.json();
        setAllPosts(result.data.reverse());
      }
    } catch (err) {
      alert(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div className="herosec flex flex-col md:flex-row justify-around items-center mt-20 max-w-7xl">
            <div className="heroleft">
              <div className="imagesec flex gap-2 mb-5">
              <img className =" h-[30px] w-[30px]  top-[200px] left-[400px] rotate-[-5deg] shadow-sm" src = {Midjour}></img>
              <div className="plus text-2xl">+</div>
              <img className =" h-[30px] w-[30px] top-[150px] rotate-[5deg] shadow-lg" src = {Openai}></img>
              </div>
              <h1 className='fah text-8xl font-bold mb-3'><span className="gradient-text">Visuals</span> <br/>from Venus</h1>
              <h3 className='f text-lg mb-7 font-regular text-gray-600'>Using the power of AI to visualize your creative thoughts & ideas <br/> in the form of illustrations, 3d art and diagrams.</h3>
              <Link to="/create-post" className="font-inter font-medium bg-[#333333] text-white px-4 py-2 rounded-md mt-[100px] shadow-xl">Create Post</Link>

          </div>

            <div className="heroright">

            <img className="venushead lg:h-[430px] lg:w-[530px] sm:h-[220px] w-[270px] rotate-[15deg]" src={Venushead}/>

            </div>


      </div>
      <div className="boxsec mt-[100px]">
        <div className="boxie w-[250px] p-10 rounded-lg shadow-sm items-center align-middle text-center">
          <div className="text-3xl mb-1">🧠</div>
          <h1 className="text-xl text-gray-600 font-semibold">Brainstorm</h1>
          <div className="para text-xs text-gray-400 mt-3">Think of your most wild ideas, something you'd want to see.</div>
        </div>
        <div className="boxie w-[250px] p-10 rounded-lg shadow-sm items-center align-middle text-center shadow-sm">
        <div className="text-3xl mb-1">🎨</div>
          <h1 className="text-xl text-gray-600 font-semibold">Create</h1>
          <div className="para text-xs text-gray-400 mt-3">Generate your ideas into visual art generated by dall-E AI</div>
        </div>
        <div className="boxie w-[250px] p-10 rounded-lg shadow-sm items-center align-middle text-center shadow-sm">
        <div className="text-3xl mb-1">🪐</div>
          <h1 className="text-xl text-gray-600 font-semibold">Share</h1>
          <div className="para text-xs text-gray-400 mt-3">Download and share your creation with the world.</div>
        </div>
      </div>
      <div>
        <h1 className="font-bold text-[#333333] text-4xl mt-[100px]">What others have made</h1>
        <p className="mt-2 text-[#999999] text-4px] max-w-[600px]">See how others have used their creativity to create some cool digital art.</p>

      </div>

      <div className='flex items-center justify-center mt-10'>
      <CarouselDemo />
      </div>
      <div className="accord">
        <h1 className="title text-4xl font-bold mt-10 text-[#333333]">FAQ.</h1>
        <AccordionDemo />
      </div>
      <Footer />
    </section>
  );
};

export default Home;
